# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/simsu/Other/projects/Py/TorrentBro/designer/Home.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(537, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Home.sizePolicy().hasHeightForWidth())
        Home.setSizePolicy(sizePolicy)
        Home.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/48x48/torrentbro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Home.setWindowIcon(icon)
        Home.setIconSize(QtCore.QSize(48, 48))
        self.centralWidget = QtWidgets.QWidget(Home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchTextbox = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchTextbox.sizePolicy().hasHeightForWidth())
        self.searchTextbox.setSizePolicy(sizePolicy)
        self.searchTextbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.searchTextbox.setObjectName("searchTextbox")
        self.horizontalLayout.addWidget(self.searchTextbox)
        self.searchButton = QtWidgets.QPushButton(self.centralWidget)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.introText = QtWidgets.QTextBrowser(self.centralWidget)
        self.introText.setObjectName("introText")
        self.verticalLayout.addWidget(self.introText)
        self.torrentView = QtWidgets.QHBoxLayout()
        self.torrentView.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.torrentView.setObjectName("torrentView")
        self.torrentList = QtWidgets.QListWidget(self.centralWidget)
        self.torrentList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentList.sizePolicy().hasHeightForWidth())
        self.torrentList.setSizePolicy(sizePolicy)
        self.torrentList.setObjectName("torrentList")
        self.torrentView.addWidget(self.torrentList)
        self.torrentInfo = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentInfo.sizePolicy().hasHeightForWidth())
        self.torrentInfo.setSizePolicy(sizePolicy)
        self.torrentInfo.setObjectName("torrentInfo")
        self.torrentInfoTabOverview = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentInfoTabOverview.sizePolicy().hasHeightForWidth())
        self.torrentInfoTabOverview.setSizePolicy(sizePolicy)
        self.torrentInfoTabOverview.setObjectName("torrentInfoTabOverview")
        self.gridLayout = QtWidgets.QGridLayout(self.torrentInfoTabOverview)
        self.gridLayout.setObjectName("gridLayout")
        self.torrentInfoBasic = QtWidgets.QTextBrowser(self.torrentInfoTabOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentInfoBasic.sizePolicy().hasHeightForWidth())
        self.torrentInfoBasic.setSizePolicy(sizePolicy)
        self.torrentInfoBasic.setObjectName("torrentInfoBasic")
        self.gridLayout.addWidget(self.torrentInfoBasic, 0, 0, 1, 1)
        self.torrentInfoDescription = QtWidgets.QTextBrowser(self.torrentInfoTabOverview)
        self.torrentInfoDescription.setOpenExternalLinks(True)
        self.torrentInfoDescription.setObjectName("torrentInfoDescription")
        self.gridLayout.addWidget(self.torrentInfoDescription, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.torrentInfoTabOverview)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.torrentInfo.addTab(self.torrentInfoTabOverview, "")
        self.torrentInfoTabDownload = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.torrentInfoTabDownload.sizePolicy().hasHeightForWidth())
        self.torrentInfoTabDownload.setSizePolicy(sizePolicy)
        self.torrentInfoTabDownload.setObjectName("torrentInfoTabDownload")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.torrentInfoTabDownload)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.torrentInfoMagnetLink = QtWidgets.QLabel(self.torrentInfoTabDownload)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentInfoMagnetLink.sizePolicy().hasHeightForWidth())
        self.torrentInfoMagnetLink.setSizePolicy(sizePolicy)
        self.torrentInfoMagnetLink.setMaximumSize(QtCore.QSize(16777215, 50))
        self.torrentInfoMagnetLink.setObjectName("torrentInfoMagnetLink")
        self.gridLayout_2.addWidget(self.torrentInfoMagnetLink, 0, 0, 1, 2)
        self.torrentInfoTorrentLink = QtWidgets.QLabel(self.torrentInfoTabDownload)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentInfoTorrentLink.sizePolicy().hasHeightForWidth())
        self.torrentInfoTorrentLink.setSizePolicy(sizePolicy)
        self.torrentInfoTorrentLink.setMaximumSize(QtCore.QSize(16777215, 50))
        self.torrentInfoTorrentLink.setObjectName("torrentInfoTorrentLink")
        self.gridLayout_2.addWidget(self.torrentInfoTorrentLink, 1, 0, 1, 2)
        self.torrentInfoFiles = QtWidgets.QTextBrowser(self.torrentInfoTabDownload)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.torrentInfoFiles.sizePolicy().hasHeightForWidth())
        self.torrentInfoFiles.setSizePolicy(sizePolicy)
        self.torrentInfoFiles.setObjectName("torrentInfoFiles")
        self.gridLayout_2.addWidget(self.torrentInfoFiles, 3, 0, 2, 2)
        self.torrentInfoFilesLabel = QtWidgets.QLabel(self.torrentInfoTabDownload)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.torrentInfoFilesLabel.sizePolicy().hasHeightForWidth())
        self.torrentInfoFilesLabel.setSizePolicy(sizePolicy)
        self.torrentInfoFilesLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.torrentInfoFilesLabel.setObjectName("torrentInfoFilesLabel")
        self.gridLayout_2.addWidget(self.torrentInfoFilesLabel, 2, 0, 1, 1)
        self.torrentInfo.addTab(self.torrentInfoTabDownload, "")
        self.torrentView.addWidget(self.torrentInfo)
        self.verticalLayout.addLayout(self.torrentView)
        Home.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 27))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        Home.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(Home)
        self.statusBar.setObjectName("statusBar")
        Home.setStatusBar(self.statusBar)
        self.settingsAction = QtWidgets.QAction(Home)
        self.settingsAction.setObjectName("settingsAction")
        self.quitAction = QtWidgets.QAction(Home)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.quitAction.setIcon(icon)
        self.quitAction.setObjectName("quitAction")
        self.menuFile.addAction(self.quitAction)
        self.menuEdit.addAction(self.settingsAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Home)
        self.torrentInfo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "TorrentBro"))
        self.searchButton.setText(_translate("Home", "Search"))
        self.introText.setHtml(_translate("Home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:600;\">TorrentBro</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Browse torrents from different search engines and download.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To start, search for a torrent using the textbox above.</p></body></html>"))
        self.label.setText(_translate("Home", "Description :"))
        self.torrentInfo.setTabText(self.torrentInfo.indexOf(self.torrentInfoTabOverview), _translate("Home", "Overview"))
        self.torrentInfoMagnetLink.setText(_translate("Home", "Magnet Link"))
        self.torrentInfoTorrentLink.setText(_translate("Home", "Torrent File Link"))
        self.torrentInfoFilesLabel.setText(_translate("Home", "Files :"))
        self.torrentInfo.setTabText(self.torrentInfo.indexOf(self.torrentInfoTabDownload), _translate("Home", "Download"))
        self.menuFile.setTitle(_translate("Home", "File"))
        self.menuEdit.setTitle(_translate("Home", "Edit"))
        self.settingsAction.setText(_translate("Home", "Settings"))
        self.quitAction.setText(_translate("Home", "Quit"))
        self.quitAction.setShortcut(_translate("Home", "Ctrl+Q"))

